<template>
  <section
    v-if="!isTicketChosen"
    class="full-screen row items-center justify-evenly q-mt-xl"
  >
    <div class="col-md-4 col-sm-12 col-xs-12">
      <div class="row items-center justify-evenly">
        <q-input
          class="col-8"
          outlined
          v-model="ticketID"
          @blur="resetTicketID"
          label="Ticket ID"
        />

        <q-btn
          class="col-2 id-input-btn"
          size="lg"
          icon="search"
          color="primary"
          :ripple="{ early: true }"
          @click="checksTicketID"
        />
      </div>
    </div>
    <h3 class="col-md-4 col-sm-12 col-xs-12 q-my-xl text-center">Or</h3>
    <div class="col-md-4 col-sm-12 col-xs-12 text-center">
      <q-btn
        label="Scan QR Code"
        color="primary"
        size="lg"
        :ripple="{ early: true }"
        v-if="!useQRCode"
        @click="useQRCode = true"
      />
      <div v-else class="q-mx-sm q-mx-sm-xl q-mx-md-lg">
        <q-btn
          class="float-right z-top"
          icon="close"
          flat
          color="white"
          :ripple="{ early: true }"
          @click="useQRCode = false"
        />
        <StreamBarcodeReader
          @decode="onQRCodeDecode"
          @loaded="onQRCodeLoad"
        ></StreamBarcodeReader>
      </div>
    </div>
  </section>

  <!-- After ticket has been chosen based on ID -->
  <section v-else class="full-screen row items-center justify-evenly q-mt-xl">
    <div class="ticket-action">
      <q-btn
        class="float-right z-top"
        icon="close"
        flat
        color="primary"
        :ripple="{ early: true }"
        @click="forceResetTicketID"
      />
      <h3>{{ ticketUserName }}</h3>
      <h5>{{ ticketUserClass }}</h5>
      <h6>{{ ticketID }}</h6>
      <div class="ticket-action-btn-container">
        <q-btn
          class="ticket-action-btn"
          :label="ticketStatus == 'Paid' ? 'Use' : 'Pay'"
          color="primary"
          size="lg"
          :ripple="{ early: true }"
          @click="changeStatus"
        />
      </div>
    </div>
  </section>
</template>

<script lang="ts">
import { defineComponent, ref } from 'vue';
import { useQuasar } from 'quasar';
import { StreamBarcodeReader } from 'vue-barcode-reader';

interface ticket {
  id: string;
  name: string;
  class: string;
}

export default defineComponent({
  name: 'ProductCarousel',
  components: { StreamBarcodeReader },
  setup() {
    //Constant for using quasar plugins
    const $q = useQuasar();

    const ticketStart = 'IIPFunFair-';
    const ticketID = ref(ticketStart);

    const resetTicketID = () => {
      if (!ticketID.value.startsWith(ticketStart)) {
        ticketID.value = 'IIPFunFair-'; //Change back the ID to default value
      }
    };

    const forceResetTicketID = () => {
      ticketID.value = ticketStart;
      isTicketChosen.value = false;
    };

    const checksTicketID = () => {
      //Checks if ticket exists on server and if it is still available
      console.log(ticketID.value);

      if (false) {
        $q.notify({
          message: 'The ticket does not exist',
          caption: 'Use QR code generated by the ticket',
          color: 'primary',
        });
      } else if (ticketStatus.value == 'used') {
        $q.notify({
          message: 'The ticket is invalid',
          caption: 'It has already been used',
          color: 'primary',
        });
      } else {
        //If ticket is not paid, add it to notPaidTickets
        //If ticket is paid but not used, add it to paidTickets

        ticketStatus.value = 'not-paid';
        ticketUserName.value = 'Kevin';
        ticketUserClass.value = 'A Level';

        isTicketChosen.value = true; //Moving to actions screen for chosen ticket
      }
    };

    const onTicketInputClicked = (ID: string) => {
      ticketID.value = ID;

      checksTicketID();
    };

    const useQRCode = ref(false);

    const unpaidTickets: Array<ticket> = [];
    const paidTickets: Array<ticket> = [];

    const onQRCodeDecode = (decodedString: string) => {
      //Checks if the scanned string is the ID
      if (decodedString.startsWith('IIPFunFair')) {
        const id = decodedString;
        //Checks if ticket has already been scanned
        if (
          !unpaidTickets.some((e) => e.id == id) &&
          !paidTickets.some((e) => e.id == id)
        ) {
          ticketID.value = id;
          checksTicketID();
        }
      } else {
        $q.notify({
          message: 'QR code cannot be identified',
          caption: 'Use QR code generated by the ticket',
          color: 'primary',
        });
      }
    };

    const onQRCodeLoad = () => {
      console.log('Loaded');
    };

    const isTicketChosen = ref(false);
    const ticketUserName = ref('');
    const ticketUserClass = ref('');
    const ticketStatus = ref(''); //'not-paid', 'paid', 'used'

    const changeStatus = () => {
      if (ticketStatus.value == 'paid') {
        //Patch status as used
      } else {
        //Patch status as paid
      }

      forceResetTicketID();
    };

    return {
      //Variables before ticket is chosen
      ticketID,
      resetTicketID,
      forceResetTicketID,
      checksTicketID,
      onTicketInputClicked,
      useQRCode,
      onQRCodeDecode,
      onQRCodeLoad,

      //Variables after ticket is chosen
      isTicketChosen,
      ticketUserName,
      ticketUserClass,
      ticketStatus,
      changeStatus,
    };
  },
});
</script>

<style lang="scss" scoped>
//Overwriting the default full-screen class to be responsive
.full-screen {
  min-height: 80vh;

  @media screen and (max-width: $breakpoint-sm-max) {
    min-height: 35vh;
  }
}
.id-input-btn {
  max-width: 70px;
}

.ticket-action {
  min-width: 500px;
  background-color: $secondary;
  padding: 30px;
  border-radius: 20px;

  @media screen and (max-width: $breakpoint-sm-max) {
    min-width: 500px;
  }

  @media screen and (max-width: $breakpoint-xs-max) {
    min-width: 350px;
  }

  .ticket-action-btn-container {
    text-align: center;
    margin-top: 50px;

    .ticket-action-btn {
      width: 400px;

      @media screen and (max-width: $breakpoint-sm-max) {
        width: 350px;
      }

      @media screen and (max-width: $breakpoint-sm-max) {
        width: 250px;
      }
    }
  }
}
</style>
