<template>
  <section class="full-screen row items-center justify-evenly q-mt-xl">
    <div class="col-md-4 col-sm-12 col-xs-12">
      <div class="row items-center justify-evenly">
        <q-input
          class="col-8"
          outlined
          v-model="ticketID"
          @blur="resetIDInput"
          label="Ticket ID"
        />

        <q-btn
          class="col-2 id-input-btn"
          size="lg"
          icon="search"
          color="primary"
          :ripple="{ early: true }"
        />
      </div>
    </div>
    <h3 class="col-md-4 col-sm-12 col-xs-12 q-my-xl text-center">Or</h3>
    <div class="col-md-4 col-sm-12 col-xs-12 text-center">
      <q-btn
        label="Scan QR Code"
        color="primary"
        size="lg"
        :ripple="{ early: true }"
        v-if="!useQRCode"
        @click="useQRCode = true"
      />
      <div v-else class="q-mx-sm q-mx-sm-xl q-mx-md-lg">
        <q-btn
          class="float-right z-top"
          icon="close"
          flat
          color="white"
          :ripple="{ early: true }"
          @click="useQRCode = false"
        />
        <StreamBarcodeReader
          @decode="onQRCodeDecode"
          @loaded="onQRCodeLoad"
        ></StreamBarcodeReader>
      </div>
    </div>
  </section>
</template>

<script lang="ts">
import { defineComponent, ref } from 'vue';
import { useQuasar } from 'quasar';
import { StreamBarcodeReader } from 'vue-barcode-reader';

interface ticket {
  id: string;
  name: string;
  class: string;
}

export default defineComponent({
  name: 'ProductCarousel',
  components: { StreamBarcodeReader },
  setup() {
    //Constant for using quasar plugins
    const $q = useQuasar();

    const ticketID = ref('IIPFunFair-');

    const resetIDInput = () => {
      ticketID.value = 'IIPFunFair-';
    };

    const useQRCode = ref(false);

    const unpaidTickets: Array<ticket> = [];
    const paidTickets: Array<ticket> = [];

    const onQRCodeDecode = (decodedString: string) => {
      //Checks if the scanned string is the ID
      if (decodedString.startsWith('IIPFunFair')) {
        const id = decodedString;
        //Checks if ticket has already been scanned
        if (
          !unpaidTickets.some((e) => e.id == id) &&
          !paidTickets.some((e) => e.id == id)
        ) {
          //Checks if ticket exists on server and if it is still available

          if (false) {
            $q.notify({
              message: 'The ticket does not exist',
              caption: 'Use QR code generated by the ticket',
              color: 'primary',
            });
          } else if (false) {
            $q.notify({
              message: 'The ticket is invalid',
              caption: 'It has already been used',
              color: 'primary',
            });
          } else {
            //If ticket is not paid, add it to notPaidTickets
            //If ticket is paid but not used, add it to paidTickets

            if (true) {
              unpaidTickets.push({
                id: 'IIPFunFair-GFD-38402',
                name: 'Kevin',
                class: 'A Level',
              });
            } else {
              paidTickets.push({
                id: 'IIPFunFair-GFD-38402',
                name: 'Kevin',
                class: 'A Level',
              });
            }
          }
        }
      } else {
        $q.notify({
          message: 'QR code cannot be identified',
          caption: 'Use QR code generated by the ticket',
          color: 'primary',
        });
      }
    };

    const onQRCodeLoad = () => {
      console.log('Loaded');
    };

    return {
      ticketID,
      resetIDInput,
      useQRCode,
      onQRCodeDecode,
      onQRCodeLoad,
    };
  },
});
</script>

<style lang="scss" scoped>
//Overwriting the default full-screen class to be responsive
.full-screen {
  min-height: 80vh;

  @media screen and (max-width: $breakpoint-sm-max) {
    min-height: 35vh;
  }
}
.id-input-btn {
  max-width: 70px;
}
</style>
